### ISSUE TITLE
[node-backend] Employee signin and signup

### ISSUE THREAD

**Issue by sunil4sonawane** [joshsoftware/peerly#10]
**Tasks:**

 - [x] Implement v1/login endpoint as per the flow

 - [x] Add logout API (this should create an entry of user token in user_blacklisted_tokens)

 - [x] Task to clean up user_black_listed token when the token in table expires expires

**Acceptance criteria:**

New / Existing users should be able to login
All users signed up from this flow should have Employee role
