### ISSUE TITLE
[node-backend] - API deployment

### ISSUE THREAD

**Issue by sunil4sonawane** [joshsoftware/peerly#49]
**Tasks:**
- [ ] Deploy node APIs on cloud server

- [ ] Test  those APIs are accessible

- [ ] Provide end point to UI team to consume those APIs
